title: Albert Gubaidullin
description: My name is Albert Gubaidullin. Feel free to contact me if you have any questions.
logo: assets/img/avatar.jpg
show_downloads: false
analytics: true


linkedin: https://www.linkedin.com/in/albert-gubaidullin/

theme: jekyll-theme-minimal
